from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    TEACHER = "TEACHER"
    STUDENT = "STUDENT"
    GUARDIAN = "GUARDIAN"

class AssignmentState(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class AssignmentTargetType(str, Enum):
    CLASS = "CLASS"
    GROUP = "GROUP"
    INDIVIDUAL = "INDIVIDUAL"

class SubmissionState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    SUBMITTED = "SUBMITTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    RESUBMITTED = "RESUBMITTED"
    COMPLETED = "COMPLETED"

class DocumentType(str, Enum):
    ASSIGNMENT_BRIEF = "ASSIGNMENT_BRIEF"
    ROSTER = "ROSTER"
    POLICY = "POLICY"
    SUBMISSION_ATTACHMENT = "SUBMISSION_ATTACHMENT"
    CLASS_MATERIAL = "CLASS_MATERIAL"

class ParseApprovalState(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"

class FeedbackAction(str, Enum):
    COMMENT = "COMMENT"
    REVISION_REQUEST = "REVISION_REQUEST"
    APPROVAL = "APPROVAL"

class ReminderType(str, Enum):
    UPCOMING = "UPCOMING"
    OVERDUE = "OVERDUE"
    ESCALATION = "ESCALATION"

class ReminderState(str, Enum):
    SCHEDULED = "SCHEDULED"
    SENT = "SENT"
    SKIPPED_QUIET = "SKIPPED_QUIET"
    SKIPPED_SUBMITTED = "SKIPPED_SUBMITTED"
    FAILED = "FAILED"

class PolicyType(str, Enum):
    QUIET_HOURS = "QUIET_HOURS"
    ESCALATION = "ESCALATION"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    CHANNEL_RULES = "CHANNEL_RULES"
