"""Add target class and student ids to documents

Revision ID: 443460ec0c3e
Revises: 7c479848b71d
Create Date: 2026-10-06 13:43:38.475200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443460ec0c3e'
down_revision: Union[str, None] = '7c479848b71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('target_class_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('target_student_ids', sa.JSON(), nullable=False, server_default='[]'))
    op.create_foreign_key(None, 'documents', 'grade_classes', ['target_class_id'], ['id'])
    op.drop_index('uq_reminder_assignment_student_type_level', table_name='reminders')
    op.drop_index('uq_student_one_class', table_name='student_enrollments')
    op.create_unique_constraint('uq_user_email_school', 'users', ['email', 'school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email_school', 'users', type_='unique')
    op.create_index('uq_student_one_class', 'student_enrollments', ['student_id'], unique=True)
    op.create_index('uq_reminder_assignment_student_type_level', 'reminders', ['assignment_id', 'target_student_id', 'reminder_type', 'escalation_level'], unique=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'target_student_ids')
    op.drop_column('documents', 'target_class_id')
    # ### end Alembic commands ###
