"""Add assignment_classes and remove target_class_id

Revision ID: 63f4ef9a0992
Revises: eb97f370994f
Create Date: 2026-10-04 07:45:22.592050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f4ef9a0992'
down_revision: Union[str, None] = 'eb97f370994f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_classes',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['grade_classes.id'], ),
    sa.PrimaryKeyConstraint('assignment_id', 'class_id')
    )
    
    # Backfill existing assignments
    op.execute(
        """
        INSERT INTO assignment_classes (assignment_id, class_id)
        SELECT id, target_class_id FROM assignments WHERE target_class_id IS NOT NULL;
        """
    )
    
    op.drop_constraint('assignments_target_class_id_fkey', 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'target_class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('target_class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('assignments_target_class_id_fkey', 'assignments', 'grade_classes', ['target_class_id'], ['id'])
    
    op.execute(
        """
        UPDATE assignments a
        SET target_class_id = ac.class_id
        FROM (SELECT assignment_id, MAX(class_id) as class_id FROM assignment_classes GROUP BY assignment_id) ac
        WHERE a.id = ac.assignment_id;
        """
    )
    
    op.drop_table('assignment_classes')
    # ### end Alembic commands ###
