"""fix assignment target_class_id

Revision ID: 7c479848b71d
Revises: 63f4ef9a0992
Create Date: 2026-10-04 09:07:32.887287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c479848b71d'
down_revision: Union[str, None] = '63f4ef9a0992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_classes')
    op.add_column('assignments', sa.Column('target_class_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'grade_classes', ['target_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'target_class_id')
    op.create_table('assignment_classes',
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='assignment_classes_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['class_id'], ['grade_classes.id'], name='assignment_classes_class_id_fkey'),
    sa.PrimaryKeyConstraint('assignment_id', 'class_id', name='assignment_classes_pkey')
    )
    # ### end Alembic commands ###
